sprite_player_a db 0,0,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,0,0
                db 0,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,0
                db PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_WHITE,PAL_WHITE,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2
                db PAL_PANEL2,PAL_CYAN2,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_CYAN2,PAL_PANEL2
                db PAL_PANEL2,PAL_CYAN,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN,PAL_PANEL2
                db 0,PAL_PANEL2,PAL_CYAN,PAL_AMBER,PAL_AMBER,PAL_CYAN,PAL_PANEL2,0
                db 0,PAL_CYAN,PAL_PANEL2,0,0,PAL_PANEL2,PAL_CYAN,0
                db PAL_CYAN,0,PAL_PANEL2,0,0,PAL_PANEL2,0,PAL_CYAN

sprite_player_b db 0,0,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,0,0
                db 0,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,0
                db PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_WHITE,PAL_WHITE,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2
                db PAL_PANEL2,PAL_CYAN2,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_CYAN2,PAL_PANEL2
                db 0,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,0
                db PAL_PANEL2,PAL_CYAN,PAL_CYAN2,PAL_AMBER,PAL_AMBER,PAL_CYAN2,PAL_CYAN,PAL_PANEL2
                db PAL_CYAN,0,PAL_PANEL2,0,0,PAL_PANEL2,0,PAL_CYAN
                db 0,PAL_PANEL2,0,0,0,0,PAL_PANEL2,0

sprite_enemy_a  db 0,0,PAL_PANEL2,PAL_RED,PAL_RED,PAL_PANEL2,0,0
                db 0,PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_PANEL2,0
                db PAL_PANEL2,PAL_RED2,PAL_RED,PAL_WHITE,PAL_WHITE,PAL_RED,PAL_RED2,PAL_PANEL2
                db PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_AMBER,PAL_AMBER,PAL_RED2,PAL_RED2,PAL_PANEL2
                db PAL_PANEL2,PAL_RED,PAL_RED2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_RED,PAL_PANEL2
                db 0,PAL_PANEL2,PAL_RED,PAL_PANEL2,PAL_PANEL2,PAL_RED,PAL_PANEL2,0
                db PAL_RED,0,PAL_PANEL2,0,0,PAL_PANEL2,0,PAL_RED
                db 0,0,PAL_RED2,0,0,PAL_RED2,0,0

sprite_enemy_b  db 0,0,PAL_PANEL2,PAL_RED,PAL_RED,PAL_PANEL2,0,0
                db 0,PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_PANEL2,0
                db PAL_PANEL2,PAL_RED2,PAL_WHITE,PAL_RED,PAL_RED,PAL_WHITE,PAL_RED2,PAL_PANEL2
                db PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_AMBER,PAL_AMBER,PAL_RED2,PAL_RED2,PAL_PANEL2
                db 0,PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_PANEL2,0
                db PAL_PANEL2,PAL_RED,PAL_RED2,PAL_PANEL2,PAL_PANEL2,PAL_RED2,PAL_RED,PAL_PANEL2
                db 0,PAL_RED,0,PAL_PANEL2,PAL_PANEL2,0,PAL_RED,0
                db PAL_RED2,0,0,0,0,0,0,PAL_RED2

sprite_enemy_flanker_a db 0,0,PAL_PANEL2,PAL_CYAN,PAL_CYAN,PAL_PANEL2,0,0
                       db 0,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,0
                       db PAL_PANEL2,PAL_CYAN2,PAL_WHITE,PAL_PANEL2,PAL_PANEL2,PAL_WHITE,PAL_CYAN2,PAL_PANEL2
                       db PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_AMBER,PAL_AMBER,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2
                       db PAL_PANEL2,PAL_CYAN,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,PAL_CYAN,PAL_PANEL2
                       db 0,PAL_CYAN2,PAL_PANEL2,0,0,PAL_PANEL2,PAL_CYAN2,0
                       db PAL_CYAN,0,PAL_PANEL2,0,0,PAL_PANEL2,0,PAL_CYAN
                       db 0,0,PAL_CYAN2,0,0,PAL_CYAN2,0,0

sprite_enemy_flanker_b db 0,0,PAL_PANEL2,PAL_CYAN,PAL_CYAN,PAL_PANEL2,0,0
                       db 0,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,0
                       db PAL_PANEL2,PAL_CYAN2,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_CYAN2,PAL_PANEL2
                       db PAL_PANEL2,PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_AMBER,PAL_WHITE,PAL_CYAN2,PAL_PANEL2
                       db 0,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,0
                       db PAL_CYAN2,0,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,0,PAL_CYAN2
                       db 0,PAL_CYAN,0,PAL_PANEL2,PAL_PANEL2,0,PAL_CYAN,0
                       db PAL_CYAN2,0,0,0,0,0,0,PAL_CYAN2

sprite_enemy_warden_a db 0,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_GATE,PAL_GATE,PAL_PANEL2,0
                      db PAL_PANEL2,PAL_GATE,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_GATE,PAL_PANEL2
                      db PAL_GATE,PAL_PANEL2,PAL_GATE,PAL_AMBER,PAL_AMBER,PAL_GATE,PAL_PANEL2,PAL_GATE
                      db PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_GATE,PAL_GATE
                      db PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2
                      db 0,PAL_PANEL2,PAL_GATE,PAL_AMBER,PAL_AMBER,PAL_GATE,PAL_PANEL2,0
                      db 0,PAL_GATE,0,PAL_PANEL2,PAL_PANEL2,0,PAL_GATE,0
                      db PAL_PANEL2,0,0,PAL_PANEL2,PAL_PANEL2,0,0,PAL_PANEL2

sprite_enemy_warden_b db 0,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_GATE,PAL_GATE,PAL_PANEL2,0
                      db PAL_PANEL2,PAL_GATE,PAL_WHITE,PAL_PANEL2,PAL_PANEL2,PAL_WHITE,PAL_GATE,PAL_PANEL2
                      db PAL_GATE,PAL_PANEL2,PAL_GATE,PAL_WHITE,PAL_WHITE,PAL_GATE,PAL_PANEL2,PAL_GATE
                      db PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_AMBER,PAL_AMBER,PAL_PANEL2,PAL_GATE,PAL_GATE
                      db 0,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_GATE,PAL_GATE,PAL_PANEL2,0
                      db PAL_PANEL2,0,PAL_GATE,PAL_AMBER,PAL_AMBER,PAL_GATE,0,PAL_PANEL2
                      db 0,PAL_GATE,0,PAL_PANEL2,PAL_PANEL2,0,PAL_GATE,0
                      db 0,0,PAL_PANEL2,0,0,PAL_PANEL2,0,0

sprite_shard_a  db 0,0,0,PAL_CYAN,0,0,0,0
                db 0,0,PAL_CYAN2,PAL_WHITE,PAL_CYAN2,0,0,0
                db 0,PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_WHITE,PAL_CYAN2,0,0
                db PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_AMBER,PAL_AMBER,PAL_WHITE,PAL_CYAN2,0
                db 0,PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_WHITE,PAL_CYAN2,0,0
                db 0,0,PAL_CYAN2,PAL_WHITE,PAL_CYAN2,0,0,0
                db 0,0,0,PAL_CYAN,0,0,0,0
                db 0,0,0,0,0,0,0,0

sprite_shard_b  db 0,0,0,0,PAL_WHITE,0,0,0
                db 0,0,0,PAL_CYAN2,PAL_WHITE,PAL_CYAN2,0,0
                db 0,0,PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_WHITE,PAL_CYAN2,0
                db 0,PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_WHITE,PAL_CYAN2,0,0
                db 0,0,PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_WHITE,0,0
                db 0,0,0,PAL_CYAN2,PAL_WHITE,0,0,0
                db 0,0,0,0,PAL_CYAN,0,0,0
                db 0,0,0,0,0,0,0,0

sprite_gate_a   db 0,0,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,0,0
                db 0,PAL_PANEL2,PAL_GATE,PAL_CYAN2,PAL_CYAN2,PAL_GATE,PAL_PANEL2,0
                db PAL_PANEL2,PAL_GATE,PAL_CYAN2,PAL_WHITE,PAL_WHITE,PAL_CYAN2,PAL_GATE,PAL_PANEL2
                db PAL_GATE,PAL_CYAN2,PAL_WHITE,PAL_GATE,PAL_GATE,PAL_WHITE,PAL_CYAN2,PAL_GATE
                db PAL_PANEL2,PAL_GATE,PAL_CYAN2,PAL_WHITE,PAL_WHITE,PAL_CYAN2,PAL_GATE,PAL_PANEL2
                db 0,PAL_PANEL2,PAL_GATE,PAL_CYAN2,PAL_CYAN2,PAL_GATE,PAL_PANEL2,0
                db 0,0,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,0,0
                db 0,0,0,0,0,0,0,0

sprite_gate_b   db 0,0,0,PAL_PANEL2,PAL_PANEL2,0,0,0
                db 0,0,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,0,0
                db 0,PAL_PANEL2,PAL_GATE,PAL_WHITE,PAL_WHITE,PAL_GATE,PAL_PANEL2,0
                db PAL_PANEL2,PAL_GATE,PAL_WHITE,PAL_CYAN2,PAL_CYAN2,PAL_WHITE,PAL_GATE,PAL_PANEL2
                db 0,PAL_PANEL2,PAL_GATE,PAL_WHITE,PAL_WHITE,PAL_GATE,PAL_PANEL2,0
                db 0,0,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,0,0
                db 0,0,0,PAL_PANEL2,PAL_PANEL2,0,0,0
                db 0,0,0,0,0,0,0,0

sprite_bitriver_mark db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
                    db 0,0,0,0,PAL_CYAN,PAL_CYAN,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN,PAL_CYAN,0,0,0,0
                    db 0,0,0,PAL_CYAN,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_CYAN,0,0
                    db 0,0,PAL_CYAN,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_PANEL2,PAL_AMBER,PAL_AMBER,PAL_PANEL2,PAL_CYAN,0,0
                    db 0,0,PAL_CYAN2,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_PANEL2,PAL_AMBER,PAL_AMBER,PAL_PANEL2,PAL_CYAN2,0,0
                    db 0,0,PAL_CYAN2,PAL_PANEL2,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_CYAN2,0,0
                    db 0,0,PAL_CYAN2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_CYAN2,0,0
                    db 0,0,PAL_CYAN2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_PANEL2,PAL_CYAN2,0,0
                    db 0,0,PAL_CYAN2,PAL_PANEL2,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_CYAN2,0,0
                    db 0,0,PAL_CYAN2,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_CYAN2,0,0
                    db 0,0,PAL_CYAN2,PAL_PANEL2,PAL_GATE,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_CYAN2,0,0
                    db 0,0,PAL_CYAN,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_CYAN,0,0
                    db 0,0,0,PAL_CYAN,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_PANEL2,PAL_CYAN,0,0
                    db 0,0,0,0,PAL_CYAN,PAL_CYAN,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN,PAL_CYAN,0,0,0,0
                    db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
                    db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

tile_floor_a db PAL_FLOOR,PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR,PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR
            db PAL_FLOOR2,PAL_CYAN,PAL_FLOOR2,PAL_FLOOR,PAL_PANEL2,PAL_FLOOR,PAL_CYAN,PAL_FLOOR2
            db PAL_PANEL2,PAL_FLOOR2,PAL_FLOOR,PAL_CYAN2,PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR
            db PAL_FLOOR,PAL_PANEL2,PAL_CYAN,PAL_FLOOR2,PAL_FLOOR,PAL_CYAN2,PAL_FLOOR2,PAL_PANEL2
            db PAL_FLOOR,PAL_FLOOR,PAL_PANEL2,PAL_FLOOR,PAL_CYAN,PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR
            db PAL_FLOOR2,PAL_CYAN2,PAL_FLOOR,PAL_PANEL2,PAL_FLOOR2,PAL_FLOOR,PAL_CYAN,PAL_FLOOR2
            db PAL_PANEL2,PAL_FLOOR,PAL_FLOOR2,PAL_CYAN,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR2,PAL_PANEL2
            db PAL_FLOOR,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR2,PAL_FLOOR,PAL_PANEL2,PAL_CYAN2,PAL_FLOOR

tile_floor_b db PAL_FLOOR,PAL_PANEL2,PAL_FLOOR2,PAL_FLOOR,PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR
            db PAL_PANEL2,PAL_FLOOR2,PAL_CYAN2,PAL_FLOOR,PAL_FLOOR,PAL_CYAN,PAL_FLOOR2,PAL_PANEL2
            db PAL_FLOOR2,PAL_CYAN,PAL_FLOOR,PAL_PANEL2,PAL_CYAN2,PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR
            db PAL_FLOOR,PAL_FLOOR2,PAL_PANEL2,PAL_CYAN,PAL_FLOOR2,PAL_FLOOR,PAL_CYAN2,PAL_FLOOR2
            db PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR2,PAL_CYAN2,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR
            db PAL_PANEL2,PAL_CYAN,PAL_FLOOR2,PAL_FLOOR,PAL_PANEL2,PAL_CYAN2,PAL_FLOOR2,PAL_PANEL2
            db PAL_FLOOR,PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR,PAL_CYAN,PAL_FLOOR2,PAL_PANEL2,PAL_FLOOR
            db PAL_FLOOR2,PAL_PANEL2,PAL_CYAN2,PAL_FLOOR,PAL_FLOOR2,PAL_FLOOR,PAL_PANEL2,PAL_FLOOR2

tile_wall_a db PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2
           db PAL_WALL2,PAL_WALL,PAL_PANEL2,PAL_WALL,PAL_WALL,PAL_PANEL2,PAL_WALL,PAL_WALL2
           db PAL_WALL2,PAL_PANEL2,PAL_WALL2,PAL_CYAN,PAL_PANEL2,PAL_WALL2,PAL_PANEL2,PAL_WALL2
           db PAL_WALL2,PAL_WALL,PAL_PANEL2,PAL_WALL2,PAL_WALL,PAL_PANEL2,PAL_CYAN2,PAL_WALL2
           db PAL_WALL2,PAL_WALL2,PAL_WALL,PAL_PANEL2,PAL_WALL2,PAL_WALL,PAL_PANEL2,PAL_WALL2
           db PAL_WALL2,PAL_PANEL2,PAL_CYAN2,PAL_WALL,PAL_PANEL2,PAL_WALL2,PAL_WALL,PAL_WALL2
           db PAL_WALL2,PAL_WALL,PAL_PANEL2,PAL_WALL2,PAL_CYAN,PAL_PANEL2,PAL_WALL,PAL_WALL2
           db PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2

tile_wall_b db PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2
           db PAL_WALL2,PAL_WALL,PAL_PANEL2,PAL_WALL,PAL_CYAN2,PAL_PANEL2,PAL_WALL,PAL_WALL2
           db PAL_WALL2,PAL_PANEL2,PAL_WALL2,PAL_PANEL2,PAL_WALL,PAL_CYAN,PAL_PANEL2,PAL_WALL2
           db PAL_WALL2,PAL_WALL,PAL_CYAN,PAL_WALL2,PAL_PANEL2,PAL_WALL,PAL_PANEL2,PAL_WALL2
           db PAL_WALL2,PAL_PANEL2,PAL_WALL,PAL_CYAN2,PAL_WALL2,PAL_PANEL2,PAL_WALL,PAL_WALL2
           db PAL_WALL2,PAL_WALL,PAL_PANEL2,PAL_WALL,PAL_PANEL2,PAL_CYAN,PAL_WALL2,PAL_WALL2
           db PAL_WALL2,PAL_PANEL2,PAL_CYAN2,PAL_PANEL2,PAL_WALL,PAL_PANEL2,PAL_WALL,PAL_WALL2
           db PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2,PAL_WALL2

tile_locked_a db PAL_PANEL2,PAL_RED,PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_PANEL2,PAL_RED,PAL_PANEL2
             db PAL_RED,PAL_PANEL2,PAL_RED2,PAL_WHITE,PAL_WHITE,PAL_RED2,PAL_PANEL2,PAL_RED
             db PAL_PANEL2,PAL_RED2,PAL_PANEL2,PAL_RED,PAL_RED,PAL_PANEL2,PAL_RED2,PAL_PANEL2
             db PAL_RED2,PAL_WHITE,PAL_RED,PAL_PANEL2,PAL_PANEL2,PAL_RED,PAL_WHITE,PAL_RED2
             db PAL_RED2,PAL_WHITE,PAL_RED,PAL_PANEL2,PAL_PANEL2,PAL_RED,PAL_WHITE,PAL_RED2
             db PAL_PANEL2,PAL_RED2,PAL_PANEL2,PAL_RED,PAL_RED,PAL_PANEL2,PAL_RED2,PAL_PANEL2
             db PAL_RED,PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_RED2,PAL_PANEL2,PAL_RED
             db PAL_PANEL2,PAL_RED,PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_PANEL2,PAL_RED,PAL_PANEL2

tile_locked_b db PAL_PANEL2,PAL_RED2,PAL_PANEL2,PAL_RED,PAL_RED,PAL_PANEL2,PAL_RED2,PAL_PANEL2
             db PAL_RED2,PAL_PANEL2,PAL_RED,PAL_WHITE,PAL_WHITE,PAL_RED,PAL_PANEL2,PAL_RED2
             db PAL_PANEL2,PAL_RED,PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_PANEL2,PAL_RED,PAL_PANEL2
             db PAL_RED,PAL_WHITE,PAL_RED2,PAL_PANEL2,PAL_PANEL2,PAL_RED2,PAL_WHITE,PAL_RED
             db PAL_RED,PAL_WHITE,PAL_RED2,PAL_PANEL2,PAL_PANEL2,PAL_RED2,PAL_WHITE,PAL_RED
             db PAL_PANEL2,PAL_RED,PAL_PANEL2,PAL_RED2,PAL_RED2,PAL_PANEL2,PAL_RED,PAL_PANEL2
             db PAL_RED2,PAL_PANEL2,PAL_RED,PAL_RED,PAL_RED,PAL_RED,PAL_PANEL2,PAL_RED2
             db PAL_PANEL2,PAL_RED2,PAL_PANEL2,PAL_RED,PAL_RED,PAL_PANEL2,PAL_RED2,PAL_PANEL2

tile_open_a db PAL_PANEL2,PAL_GATE,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,PAL_GATE,PAL_PANEL2
           db PAL_GATE,PAL_PANEL2,PAL_CYAN2,PAL_WHITE,PAL_WHITE,PAL_CYAN2,PAL_PANEL2,PAL_GATE
           db PAL_PANEL2,PAL_CYAN2,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_CYAN2,PAL_PANEL2
           db PAL_CYAN2,PAL_WHITE,PAL_GATE,PAL_PANEL2,PAL_PANEL2,PAL_GATE,PAL_WHITE,PAL_CYAN2
           db PAL_CYAN2,PAL_WHITE,PAL_GATE,PAL_PANEL2,PAL_PANEL2,PAL_GATE,PAL_WHITE,PAL_CYAN2
           db PAL_PANEL2,PAL_CYAN2,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_CYAN2,PAL_PANEL2
           db PAL_GATE,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,PAL_GATE
           db PAL_PANEL2,PAL_GATE,PAL_PANEL2,PAL_CYAN2,PAL_CYAN2,PAL_PANEL2,PAL_GATE,PAL_PANEL2

tile_open_b db PAL_PANEL2,PAL_WHITE,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_WHITE,PAL_PANEL2
           db PAL_WHITE,PAL_PANEL2,PAL_GATE,PAL_CYAN2,PAL_CYAN2,PAL_GATE,PAL_PANEL2,PAL_WHITE
           db PAL_PANEL2,PAL_GATE,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_GATE,PAL_PANEL2
           db PAL_GATE,PAL_CYAN2,PAL_WHITE,PAL_PANEL2,PAL_PANEL2,PAL_WHITE,PAL_CYAN2,PAL_GATE
           db PAL_GATE,PAL_CYAN2,PAL_WHITE,PAL_PANEL2,PAL_PANEL2,PAL_WHITE,PAL_CYAN2,PAL_GATE
           db PAL_PANEL2,PAL_GATE,PAL_PANEL2,PAL_WHITE,PAL_WHITE,PAL_PANEL2,PAL_GATE,PAL_PANEL2
           db PAL_WHITE,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_WHITE
           db PAL_PANEL2,PAL_WHITE,PAL_PANEL2,PAL_GATE,PAL_GATE,PAL_PANEL2,PAL_WHITE,PAL_PANEL2

tile_surge_a db PAL_FLOOR,PAL_RED2,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR,PAL_PANEL2,PAL_RED2,PAL_FLOOR
            db PAL_RED2,PAL_FLOOR2,PAL_CYAN2,PAL_PANEL2,PAL_PANEL2,PAL_CYAN2,PAL_FLOOR2,PAL_RED2
            db PAL_PANEL2,PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_AMBER,PAL_WHITE,PAL_CYAN2,PAL_PANEL2
            db PAL_FLOOR,PAL_PANEL2,PAL_AMBER,PAL_RED,PAL_RED,PAL_AMBER,PAL_PANEL2,PAL_FLOOR
            db PAL_FLOOR,PAL_PANEL2,PAL_AMBER,PAL_RED,PAL_RED,PAL_AMBER,PAL_PANEL2,PAL_FLOOR
            db PAL_PANEL2,PAL_CYAN2,PAL_WHITE,PAL_AMBER,PAL_AMBER,PAL_WHITE,PAL_CYAN2,PAL_PANEL2
            db PAL_RED2,PAL_FLOOR2,PAL_CYAN2,PAL_PANEL2,PAL_PANEL2,PAL_CYAN2,PAL_FLOOR2,PAL_RED2
            db PAL_FLOOR,PAL_RED2,PAL_PANEL2,PAL_FLOOR,PAL_FLOOR,PAL_PANEL2,PAL_RED2,PAL_FLOOR

tile_surge_b db PAL_FLOOR,PAL_PANEL2,PAL_RED2,PAL_FLOOR,PAL_FLOOR,PAL_RED2,PAL_PANEL2,PAL_FLOOR
            db PAL_PANEL2,PAL_CYAN2,PAL_FLOOR2,PAL_RED2,PAL_RED2,PAL_FLOOR2,PAL_CYAN2,PAL_PANEL2
            db PAL_RED2,PAL_FLOOR2,PAL_CYAN2,PAL_WHITE,PAL_WHITE,PAL_CYAN2,PAL_FLOOR2,PAL_RED2
            db PAL_FLOOR,PAL_RED2,PAL_WHITE,PAL_AMBER,PAL_AMBER,PAL_WHITE,PAL_RED2,PAL_FLOOR
            db PAL_FLOOR,PAL_RED2,PAL_WHITE,PAL_AMBER,PAL_AMBER,PAL_WHITE,PAL_RED2,PAL_FLOOR
            db PAL_RED2,PAL_FLOOR2,PAL_CYAN2,PAL_WHITE,PAL_WHITE,PAL_CYAN2,PAL_FLOOR2,PAL_RED2
            db PAL_PANEL2,PAL_CYAN2,PAL_FLOOR2,PAL_RED2,PAL_RED2,PAL_FLOOR2,PAL_CYAN2,PAL_PANEL2
            db PAL_FLOOR,PAL_PANEL2,PAL_RED2,PAL_FLOOR,PAL_FLOOR,PAL_RED2,PAL_PANEL2,PAL_FLOOR

STAR_COUNT equ 16
starfield  dw 24, 18, PAL_CYAN
           dw 62, 28, PAL_WHITE
           dw 110, 12, PAL_CYAN
           dw 182, 22, PAL_WHITE
           dw 238, 18, PAL_CYAN
           dw 298, 26, PAL_WHITE
           dw 36, 176, PAL_CYAN
           dw 88, 188, PAL_WHITE
           dw 140, 182, PAL_CYAN
           dw 210, 190, PAL_WHITE
           dw 280, 178, PAL_CYAN
           dw 304, 150, PAL_WHITE
           dw 14, 98, PAL_CYAN
           dw 308, 74, PAL_WHITE
           dw 286, 54, PAL_CYAN
           dw 8, 144, PAL_WHITE

palette_data db 0,0,0
             db 2,3,8
             db 4,7,14
             db 5,10,18
             db 8,14,22
             db 0,36,42
             db 12,52,58
             db 63,63,63
             db 63,42,8
             db 48,8,8
             db 63,18,18
             db 12,16,22
             db 20,28,38
             db 6,12,16
             db 10,20,24
             db 10,46,52
             db 50,12,18
             db 18,60,56
PALETTE_BYTES equ ($ - palette_data)

font5x7 db 0Eh,11h,11h,1Fh,11h,11h,11h
        db 1Eh,11h,11h,1Eh,11h,11h,1Eh
        db 0Eh,11h,10h,10h,10h,11h,0Eh
        db 1Eh,11h,11h,11h,11h,11h,1Eh
        db 1Fh,10h,10h,1Eh,10h,10h,1Fh
        db 1Fh,10h,10h,1Eh,10h,10h,10h
        db 0Eh,11h,10h,17h,11h,11h,0Fh
        db 11h,11h,11h,1Fh,11h,11h,11h
        db 1Fh,04h,04h,04h,04h,04h,1Fh
        db 01h,01h,01h,01h,11h,11h,0Eh
        db 11h,12h,14h,18h,14h,12h,11h
        db 10h,10h,10h,10h,10h,10h,1Fh
        db 11h,1Bh,15h,15h,11h,11h,11h
        db 11h,19h,15h,13h,11h,11h,11h
        db 0Eh,11h,11h,11h,11h,11h,0Eh
        db 1Eh,11h,11h,1Eh,10h,10h,10h
        db 0Eh,11h,11h,11h,15h,12h,0Dh
        db 1Eh,11h,11h,1Eh,14h,12h,11h
        db 0Fh,10h,10h,0Eh,01h,01h,1Eh
        db 1Fh,04h,04h,04h,04h,04h,04h
        db 11h,11h,11h,11h,11h,11h,0Eh
        db 11h,11h,11h,11h,11h,0Ah,04h
        db 11h,11h,11h,15h,15h,15h,0Ah
        db 11h,11h,0Ah,04h,0Ah,11h,11h
        db 11h,11h,0Ah,04h,04h,04h,04h
        db 1Fh,01h,02h,04h,08h,10h,1Fh
        db 0Eh,11h,13h,15h,19h,11h,0Eh
        db 04h,0Ch,04h,04h,04h,04h,0Eh
        db 0Eh,11h,01h,02h,04h,08h,1Fh
        db 1Eh,01h,01h,06h,01h,01h,1Eh
        db 02h,06h,0Ah,12h,1Fh,02h,02h
        db 1Fh,10h,10h,1Eh,01h,01h,1Eh
        db 06h,08h,10h,1Eh,11h,11h,0Eh
        db 1Fh,01h,02h,04h,08h,08h,08h
        db 0Eh,11h,11h,0Eh,11h,11h,0Eh
        db 0Eh,11h,11h,0Fh,01h,02h,0Ch
        db 00h,00h,00h,00h,00h,0Ch,0Ch
        db 00h,00h,00h,00h,00h,00h,00h
